include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the

  rules:
    prefer_const_constructors: false
    prefer_final_fields:  false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    avoid_print: false

    exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/generated_plugin_registrant.dart'
